"use client";

import { useEffect, useMemo, useState } from "react";
import type { CompetitionPreferences, Match, Team } from "@/lib/types";

const STORAGE_KEY = "clubpulse-preferences";
type GamePayload = { match?: Match; teams?: Team[]; competition?: { id: string; name: string; season?: string; imageUrl?: string }; error?: string };
type StandingRow = { rank:number; teamId:string; teamName:string; imageUrl?:string; played:number; wins:number; draws:number; losses:number; goalsFor:number; goalsAgainst:number; goalDifference:number; points:number };
type StandingsPayload = { standings?: StandingRow[]; note?: string; error?: string };
type ReportPayload = { goals?: { teamId?:string; teamName?:string; player:string; minute:string }[]; statistics?: { label:string; home:string; away:string }[]; lineups?: { teamId?:string; teamName?:string; player:string; number?:string; position?:string; role:string }[]; availability?: { goals:boolean; statistics:boolean; lineups:boolean } };

function normalizeArtworkSrc(src?: string) { if (!src) return undefined; return `${src.replace(/\/(?:tiny|small|medium|large|original)\/?$/i, "")}/tiny`; }
function formatTime(date:string) { return new Intl.DateTimeFormat("en-GB", { hour:"2-digit", minute:"2-digit" }).format(new Date(date)); }
function formatDate(date:string) { return new Intl.DateTimeFormat("en-GB", { weekday:"long", day:"numeric", month:"long", year:"numeric" }).format(new Date(date)); }
function readPreferences(): CompetitionPreferences | null { try { const value=window.localStorage.getItem(STORAGE_KEY); if(!value)return null; const parsed=JSON.parse(value) as CompetitionPreferences; return Array.isArray(parsed.competitionIds)&&parsed.teamIdsByCompetition?parsed:null; } catch { return null; } }
function TeamLogo({team,size="h-12 w-12"}:{team?:Team;size?:string}) { const [failed,setFailed]=useState(false); const src=normalizeArtworkSrc(team?.imageUrl); return src&&!failed?<img src={src} alt="" onError={()=>setFailed(true)} className={`${size} shrink-0 object-contain`}/>:<div className={`flex ${size} shrink-0 items-center justify-center rounded-full bg-slate-800 text-lg`}>⚽</div>; }
function StandingLogo({src}:{src?:string}) { const [failed,setFailed]=useState(false); const image=normalizeArtworkSrc(src); return image&&!failed?<img src={image} alt="" onError={()=>setFailed(true)} className="h-7 w-7 shrink-0 object-contain"/>:<span className="flex h-7 w-7 items-center justify-center">⚽</span>; }

export default function GameDetail({gameId}:{gameId:string}) {
 const [game,setGame]=useState<GamePayload|null>(null), [standings,setStandings]=useState<StandingsPayload|null>(null), [report,setReport]=useState<ReportPayload|null>(null), [preferences,setPreferences]=useState<CompetitionPreferences|null>(null);
 useEffect(()=>setPreferences(readPreferences()),[]);
 useEffect(()=>{ const controller=new AbortController(); void fetch(`/api/games/${encodeURIComponent(gameId)}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{const p=await r.json() as GamePayload;if(!r.ok)throw new Error(p.error);setGame(p);if(p.match?.competitionId) void fetch(`/api/competitions/${encodeURIComponent(p.match.competitionId)}/standings`,{signal:controller.signal,cache:"no-store"}).then(async s=>setStandings(await s.json()));if(p.match?.status==="finished"||p.match?.homeScore!==undefined) void fetch(`/api/games/${encodeURIComponent(gameId)}/report`,{signal:controller.signal,cache:"no-store"}).then(async s=>setReport(await s.json()));}).catch(e=>{if(!(e instanceof DOMException&&e.name==="AbortError"))setGame({error:e instanceof Error?e.message:"Game unavailable"});});return()=>controller.abort();},[gameId]);
 const teamMap=useMemo(()=>new Map((game?.teams??[]).map(t=>[t.id,t])),[game?.teams]); const match=game?.match;
 if(!game)return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-5 py-10 text-slate-400">Loading game…</div></main>;
 if(!match)return <main className="min-h-screen bg-slate-950 text-white"><div className="mx-auto max-w-6xl px-5 py-10"><a href="/" className="text-sky-300">← Dashboard</a><div className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-8 text-slate-400">{game.error??"Game not found."}</div></div></main>;
 const home=teamMap.get(match.homeTeamId),away=teamMap.get(match.awayTeamId),hasScore=match.homeScore!==undefined&&match.awayScore!==undefined,isCompleted=match.status==="finished"||hasScore; const selected=preferences?.teamIdsByCompetition?.[match.competitionId]??[], followsAll=Boolean(preferences?.competitionIds?.includes(match.competitionId)&&selected.length===0), followed=(id:string)=>followsAll||selected.includes(id);
 const goalsFor=(id:string,name?:string)=>report?.goals?.filter(g=>g.teamId===id||(!g.teamId&&g.teamName===name))??[]; const homeGoals=goalsFor(match.homeTeamId,home?.name),awayGoals=goalsFor(match.awayTeamId,away?.name);
 const lineupFor=(id:string,name?:string)=>report?.lineups?.filter(p=>p.teamId===id||(!p.teamId&&p.teamName===name))??[];
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-5"><a href="/" className="text-2xl font-black">ClubPulse</a><a href="/" className="rounded-full border border-slate-700 bg-slate-900 px-4 py-2 text-sm font-semibold text-slate-300">← Dashboard</a></div></header><div className="mx-auto max-w-6xl space-y-8 px-5 py-8">
 <section><div className="mb-3 text-xs font-black uppercase tracking-[.16em] text-slate-500">{formatDate(match.date)}</div><article className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 px-5 py-3 text-xs font-semibold text-slate-400">{match.competition}</div><div className="grid grid-cols-[1fr_auto_1fr] items-start gap-3 px-4 py-6 sm:gap-6 sm:px-5"><div className="flex justify-end gap-3"><div className="text-right"><div className="font-bold sm:text-lg">{home?.name??"Unknown team"}{followed(match.homeTeamId)&&<span className="ml-1 text-amber-400">★</span>}</div>{isCompleted&&homeGoals.map((g,i)=><div key={i} className="mt-1 text-xs text-slate-400">{g.player} {g.minute}{g.minute&&!g.minute.includes("'")?"'":""}</div>)}</div><TeamLogo team={home}/></div><div className="min-w-20 text-center sm:min-w-24">{hasScore?<div className="rounded-xl bg-white px-3 py-2 text-xl font-black text-slate-950 sm:text-2xl">{match.homeScore} - {match.awayScore}</div>:<div><div className="text-[10px] font-bold uppercase text-slate-500">Kick-off</div><div className="mt-1 text-lg font-black">{formatTime(match.date)}</div></div>}</div><div className="flex gap-3"><TeamLogo team={away}/><div><div className="font-bold sm:text-lg">{away?.name??"Unknown team"}{followed(match.awayTeamId)&&<span className="ml-1 text-amber-400">★</span>}</div>{isCompleted&&awayGoals.map((g,i)=><div key={i} className="mt-1 text-xs text-slate-400">{g.player} {g.minute}{g.minute&&!g.minute.includes("'")?"'":""}</div>)}</div></div></div>{match.venue&&<div className="border-t border-slate-800 px-5 py-3 text-xs text-slate-500">📍 {match.venue}</div>}</article></section>
 {isCompleted&&<><section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 className="border-b border-slate-800 px-5 py-4 text-lg font-black">Statistics</h2>{!report?<div className="p-8 text-sm text-slate-500">Loading statistics…</div>:report.statistics?.length?<div className="divide-y divide-slate-800">{report.statistics.map((s,i)=><div key={`${s.label}-${i}`} className="grid grid-cols-[1fr_1.4fr_1fr] items-center px-5 py-3 text-sm"><strong className="text-right text-white">{s.home}</strong><span className="text-center text-slate-400">{s.label}</span><strong className="text-white">{s.away}</strong></div>)}</div>:<div className="p-8 text-sm text-slate-500">Match statistics are not available from the provider for this game.</div>}</section>
 <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><h2 className="border-b border-slate-800 px-5 py-4 text-lg font-black">Lineups</h2>{!report?<div className="p-8 text-sm text-slate-500">Loading lineups…</div>:report.lineups?.length?<div className="grid gap-0 md:grid-cols-2"><Lineup title={home?.name??"Home"} players={lineupFor(match.homeTeamId,home?.name)}/><Lineup title={away?.name??"Away"} players={lineupFor(match.awayTeamId,away?.name)}/></div>:<div className="p-8 text-sm text-slate-500">Lineups are not available from the provider for this game.</div>}</section></>}
 <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 px-5 py-4"><h1 className="text-lg font-black">{match.competition} table</h1>{game.competition?.season&&<p className="mt-1 text-xs text-slate-500">Season {game.competition.season}</p>}</div>{!standings?<div className="p-8 text-sm text-slate-500">Loading standings…</div>:standings.standings?.length?<div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-950/50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Pos</th><th className="px-3 py-3 text-left">Team</th>{["P","W","D","L","GD","Pts"].map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{standings.standings.map(r=><tr key={r.teamId} className={`border-t border-slate-800 ${r.teamId===match.homeTeamId||r.teamId===match.awayTeamId?"bg-slate-800/60":""}`}><td className="px-4 py-3 text-center">{r.rank}</td><td className="px-3 py-3"><div className="flex items-center gap-3"><StandingLogo src={r.imageUrl}/><span className="font-semibold">{r.teamName}</span></div></td>{[r.played,r.wins,r.draws,r.losses,r.goalDifference>0?`+${r.goalDifference}`:r.goalDifference,r.points].map((v,i)=><td key={i} className={`px-3 py-3 text-center ${i===5?"font-black text-white":"text-slate-400"}`}>{v}</td>)}</tr>)}</tbody></table></div>:<div className="p-8 text-sm text-slate-500">{standings.note??standings.error??"Standings are not available for this competition."}</div>}</section>
 </div></main>;
}
function Lineup({title,players}:{title:string;players:{player:string;number?:string;position?:string;role:string}[]}) { const starters=players.filter(p=>!p.role.toLowerCase().includes("sub")),subs=players.filter(p=>p.role.toLowerCase().includes("sub")); const group=(label:string,items:typeof players)=><div className="mt-4"><div className="mb-2 text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</div>{items.map((p,i)=><div key={`${p.player}-${i}`} className="flex items-center gap-3 border-t border-slate-800 py-2 text-sm"><span className="w-6 text-right text-slate-500">{p.number??""}</span><span className="font-semibold text-slate-200">{p.player}</span>{p.position&&<span className="ml-auto text-xs text-slate-500">{p.position}</span>}</div>)}</div>; return <div className="border-slate-800 p-5 md:first:border-r"><h3 className="font-black">{title}</h3>{group("Starting XI",starters)}{subs.length>0&&group("Substitutes",subs)}</div>; }
